services:
    mysql:
        container_name: local-mysql
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3310:3306
        expose:
            - 3310
        volumes:
            - G:\OpenClassroom\P7\P7_taillepierre_nicolas\my-db:\var\lib\mysql
volumes:
    my-db:
